name: paperautoupdate
main: io.github.yey007
version: 1.0
author: yey007
description: Automatically updates paper.jar when there is a new version
commands:
  update:
    description: Updates paper.jar to latest version manually.
    usage: /update
    permission: paperautoupdate.update
    permission-message: You don't have the permission for paperautoupdate.update
permissions:
  paperautoupdate.*:
    description: Gives access to auto update commands
    children:
      paperautoupdate.update: op
  paperautoupdate.update:
    description: Gives access to update command
    default: op