name: paperautoupdate
main: io.github.yey007.paperautoupdate.Main
version: 1.2.8
author: yey007
api-version: 1.15
description: Automatically updates paper.jar when there is a new version
commands:
  paperautoupdate:
    description: The basis for all paperautoupdate commands
    usage: /paperautoupdate
    permission: paperautoupdate
    permission-message: You do not have the permission for paperautoupdate
    aliases: [PaperAutoUpdate, pau, updater]
permissions:
  paperautoupdate:
    description: Gives access to all auto update commands
    children:
      paperautoupdate.update: true
  paperautoupdate.update:
    description: Gives access to update command
    default: op