name: paperautoupdate
main: io.github.yey007.paperautoupdate.Main
version: 1.1
author: yey007
api-version: 1.15
description: Automatically updates paper.jar when there is a new version
commands:
  update:
    description: Updates paper.jar to latest version manually.
    usage: /update
    permission: paperautoupdate.update
    permission-message: You do not have the permission for paperautoupdate.update
permissions:
  paperautoupdate.*:
    description: Gives access to all auto update commands
    children:
      paperautoupdate.update: true
  paperautoupdate.update:
    description: Gives access to update command
    default: op